import os

def normalize_text(s, sep_token=" \n "):
    s = s.replace("\n", sep_token)
    s = s.replace("  ", " ")
    s = s.replace(" ,", ",")
    s = s.replace(" .", ".")
    s = s.replace(" ?", "?")
    s = s.replace(" !", "!")
    s = s.replace(" :", ":")
    s = s.replace(" ;", ";")
    s = s.replace(" %", "%")
    s = s.replace(" /", "/")
    s = s.replace(" ' ", "'")
    s = s.replace("( ", "(")
    s = s.replace(" )", ")")
    s = s.replace(" - ", "-")
    s = s.replace(" -", "-")
    s = s.replace("- ", "-")
    s = s.replace(" -- ", "--")
    s = s.replace(" --", "--")
    s = s.replace("-- ", "--")
    s = s.replace("`` ", '"')
    s = s.replace(" ''", '"')
    s = s.replace("``", '"')
    s = s.replace("''", '"')
    s = s.replace(" '", "'")
    s = s.replace("' ", "'")
    s = s.replace("“", " ")
    s = s.replace("”", " ")
    s = s.replace("„", " ")
    s = s.strip()
    return s